package lisandra.domain;
// Generated 23/03/2019 11:56:18 PM by Hibernate Tools 4.3.1



/**
 * Casa generated by hbm2java
 */
public class Casa  implements java.io.Serializable {


     private Integer idCasa;
     private Usuario usuario;
     private String lugar;

    public Casa() {
    }

	
    public Casa(Usuario usuario) {
        this.usuario = usuario;
    }
    public Casa(Usuario usuario, String lugar) {
       this.usuario = usuario;
       this.lugar = lugar;
    }
   
    public Integer getIdCasa() {
        return this.idCasa;
    }
    
    public void setIdCasa(Integer idCasa) {
        this.idCasa = idCasa;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }




}


